--CREAR TABLAS
CREATE TABLE SUCURSAL (COD_SUC NUMBER(5) CONSTRAINT CODSUC_PK PRIMARY KEY, NOM_SUC VARCHAR2(150), DIR_SUC VARCHAR2(150), KIL_SUC VARCHAR2(150));

CREATE TABLE VEHICULO (COD_VEHICULO NUMBER(5) CONSTRAINT CODVEHICULO_PK PRIMARY KEY, MODELO VARCHAR2(70), MARCA VARCHAR2(30), PLACA VARCHAR2(8), 
KILOMETRAJE NUMBER(8));

CREATE TABLE CATEGORIA (COD_CAT NUMBER(5) CONSTRAINT CODCAT_PK PRIMARY KEY, NOM_CAT VARCHAR2(150), SALARIO NUMBER(10,4));

CREATE TABLE EMPLEADO (COD_EMP NUMBER(5) CONSTRAINT CODEMP_PK PRIMARY KEY, NOM_EMP VARCHAR2(150), APE_EMP VARCHAR2(150), cat_emp NUMBER(5) 
CONSTRAINT CAT_FK REFERENCES CATEGORIA(COD_CAT), DIREC_EMP VARCHAR2(150), DPI_EMP NUMBER(13), FECHA_ALTA DATE, FECHA_NAC DATE, 
TELEFONO NUMBER(8));

CREATE TABLE ASIGNACION (COD_ASIGNACION NUMBER(5) CONSTRAINT CODASIGNACION_PK PRIMARY KEY, COD_EMPLEADO NUMBER(5) CONSTRAINT CODEMPLEADO_FK 
REFERENCES EMPLEADO(COD_EMP), COD_VEHICULO NUMBER(5) CONSTRAINT CODVEHICULO_FK REFERENCES VEHICULO(COD_VEHICULO), KILOINICIAL NUMBER(8), 
KILOFINAL NUMBER(8), FECHAINICIOCOMISION DATE, FECHAFINALCOMISION DATE, NOMBREASIGNA VARCHAR(150), CODEMPASIGNA NUMBER(5) CONSTRAINT 
CODSUCURSAL_FK REFERENCES SUCURSAL(COD_SUC));

--RESTRINCIONES

ALTER TABLE EMPLEADO
ADD CONSTRAINT CK_DPI_EMP
CHECK(REGEXP_LIKE (DPI_EMP, '[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'));

ALTER TABLE EMPLEADO
ADD CONSTRAINT CK_TELEFONO
CHECK(REGEXP_LIKE (TELEFONO, '[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'));

--REGLAS DE NEGOCIO
ALTER TABLE EMPLEADO  
ADD CONSTRAINT UNI_DPI UNIQUE (DPI_EMP);

ALTER TABLE VEHICULO
ADD CONSTRAINT UNI_PLACA UNIQUE (PLACA);

--AUDITORIA DEL NEGOCIO
CREATE TABLE EMPLEADODEBAJA (NCOD_EMP NUMBER(5), OCOD_EMP NUMBER(5), NNOM_EMP VARCHAR2(150), ONOM_EMP VARCHAR2(150), NAPE_EMP VARCHAR2(150), 
OAPE_EMP VARCHAR2(150), NCAT_EMP NUMBER(5), OCAT_EMP NUMBER(5), NFECHA_ALTA DATE,  OFECHA_ALTA DATE, NCOD_SUC NUMBER(5), OCOD_SUC NUMBER(5), 
NCOD_VEHICULO NUMBER(5), OCOD_VEHICULO NUMBER(5));
